"""
Generates a runnable Python script for one arm of an experiment.

The generated script:
  - Imports run_exp63_continuous_multiday_steady_state as e63
  - Calls e63.run_continuous_experiment() with the ArmSpec's parameters
  - Prints EXPERIMENT_RESULT_JSON:<json> on the last line of stdout
    (the executor parses this to get metrics)

This template approach is far more reliable than asking the LLM to write
free-form Python — the only LLM output that matters is the JSON parameter spec.
"""
from __future__ import annotations

import json
import textwrap
from datetime import date
from pathlib import Path

from .models import SimRun


_SCRIPT_TEMPLATE = '''\
"""
Experiment {exp_number} run {run_id} — {description}
Auto-generated by experimenter on {date}
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent.parent.parent  # scripts/
ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(ROOT / "backend"))
sys.path.insert(0, str(SCRIPT_DIR))

import run_exp63_continuous_multiday_steady_state as e63  # noqa: E402

# --- GENERATED PARAMETERS ---
N_SITES = {n_sites}
NUM_DAYS = {num_days}
FLEET = {fleet_size}
SCALE = {demand_scale}
PLUGS = {plugs_per_site}
CHARGER_KW = {charger_kw}
BATTERY_KWH = {battery_kwh_repr}
DEPOT_CELLS = {depot_h3_cells_repr}
MIN_PLUG = {min_plug_repr}
CHARGING_QUEUE_POLICY = {charging_queue_policy_repr}
VEHICLE_PRESET = {vehicle_preset_repr}
REPOSITION_ALPHA = {reposition_alpha_repr}
DEMAND_CONFIG = {demand_config_repr}
# --- END GENERATED ---


def _maybe_generate_demand() -> None:
    """If demand_config is set, generate synthetic demand parquet before running sim."""
    if DEMAND_CONFIG is None:
        return
    from demand_model.config import DemandModelConfig
    from demand_model.generate import generate_demand

    config = DemandModelConfig.from_dict(DEMAND_CONFIG)
    fp = config.fingerprint()
    output_path = ROOT / "data" / "generated" / f"demand_{{fp}}.parquet"

    if not output_path.exists():
        print(f"Generating synthetic demand (fingerprint={{fp}}) ...")
        generate_demand(config, output_path=output_path)
    else:
        print(f"Reusing cached demand parquet: {{output_path}}")

    os.environ["REQUESTS_PATH"] = str(output_path)


def main() -> None:
    _maybe_generate_demand()

    out = e63.run_continuous_experiment(
        N_SITES,
        NUM_DAYS,
        demand_scale=SCALE,
        fleet_size=FLEET,
        plugs_per_site=PLUGS,
        charger_kw=CHARGER_KW,
        battery_kwh=BATTERY_KWH,
        depot_h3_cells=DEPOT_CELLS,
        min_plug_duration_minutes=MIN_PLUG,
        charging_queue_policy=CHARGING_QUEUE_POLICY,
        vehicle_preset=VEHICLE_PRESET,
        reposition_alpha=REPOSITION_ALPHA,
        show_trip_progress=True,
        trip_bar_desc="exp{exp_number}_{run_id}",
    )
    m = out["metrics"]
    daily = out.get("daily", [])

    result = {{
        "served_pct": m.get("served_pct"),
        "p10_wait_min": m.get("p10_wait_min"),
        "median_wait_min": m.get("median_wait_min"),
        "p90_wait_min": m.get("p90_wait_min"),
        "sla_adherence_pct": m.get("sla_adherence_pct"),
        "charger_utilization_pct": m.get("charger_utilization_pct"),
        "fleet_battery_pct": m.get("fleet_battery_pct"),
        "repositioning_pct": m.get("repositioning_pct"),
        "contribution_margin_per_trip": m.get("contribution_margin_per_trip"),
        "depot_queue_p90_min": m.get("depot_queue_p90_min"),
        "depot_queue_max_at_site": m.get("depot_queue_max_at_site"),
        "avg_dispatch_distance": m.get("avg_dispatch_distance"),
        "deadhead_pct": m.get("deadhead_pct"),
        "trips_per_vehicle_per_day": m.get("trips_per_vehicle_per_day"),
        "total_system_cost_per_trip": m.get("total_system_cost_per_trip"),
        "energy_cost": m.get("energy_cost"),
        "demand_cost": m.get("demand_cost"),
        "maintenance_cost": m.get("maintenance_cost"),
        "fleet_fixed_cost": m.get("fleet_fixed_cost"),
        "infra_cost": m.get("infra_cost"),
        "total_system_cost": m.get("total_system_cost"),
        "system_margin_per_trip": m.get("system_margin_per_trip"),
        "depreciation_per_vehicle_day": m.get("depreciation_per_vehicle_day"),
        "revenue_total": m.get("revenue_total"),
        "avg_revenue_per_trip": m.get("avg_revenue_per_trip"),
        "daily_served_pct": [x["served_pct"] for x in daily],
        "depot_h3_cells": out.get("depot_h3_cells", []),
        "n_sites": out.get("n_sites"),
        "num_days": out.get("num_days"),
        "vehicle_preset": VEHICLE_PRESET or "tesla",
        "battery_kwh": BATTERY_KWH,
    }}

    # Flush human-readable table to stdout before the JSON marker
    site_kw = PLUGS * CHARGER_KW
    fleet_kw = N_SITES * site_kw
    cost_trip = result.get("total_system_cost_per_trip", 0) or 0
    print(f"\\nExp{exp_number} run={run_id!r}: {{PLUGS}}p×{{CHARGER_KW:g}} kW, N={{N_SITES}}, "
          f"fleet={{FLEET}}, scale={{SCALE}}, {{NUM_DAYS}}d, preset={{VEHICLE_PRESET or 'tesla'}}")
    print(f"  served%={{result['served_pct']:.2f}}  p90_wait={{result['p90_wait_min']:.2f}} min  "
          f"cost/trip=${{cost_trip:.2f}}  "
          f"chgU={{result['charger_utilization_pct']:.1f}}%  fleetSOC={{result['fleet_battery_pct']:.1f}}%")
    if result["daily_served_pct"]:
        ds = ", ".join(f"{{x:.1f}}" for x in result["daily_served_pct"])
        print(f"  daily_served%: {{ds}}")
    print(f"  depots: {{result['depot_h3_cells']}}")
    print(f"  site_kW={{site_kw:.0f}}  fleet_kW={{fleet_kw:.0f}}")

    # Machine-readable marker — MUST be last line; executor parses this
    print("EXPERIMENT_RESULT_JSON:" + json.dumps(result))


if __name__ == "__main__":
    main()
'''


def _repr(v: object) -> str:
    """Python literal repr suitable for embedding in generated source."""
    if v is None:
        return "None"
    if isinstance(v, list):
        return repr(v)
    if isinstance(v, str):
        return repr(v)
    return repr(v)


def generate_script(run: SimRun, exp_number: int, output_dir: Path) -> Path:
    """
    Write a self-contained Python script for `run` to `output_dir`.
    Returns the path to the written file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / f"exp{exp_number}_{run.run_id}.py"

    source = _SCRIPT_TEMPLATE.format(
        exp_number=exp_number,
        run_id=run.run_id,
        description=run.description,
        date=date.today().isoformat(),
        n_sites=run.n_sites,
        num_days=run.num_days,
        fleet_size=run.fleet_size,
        demand_scale=run.demand_scale,
        plugs_per_site=run.plugs_per_site,
        charger_kw=run.charger_kw,
        battery_kwh_repr=_repr(run.battery_kwh),
        depot_h3_cells_repr=_repr(run.depot_h3_cells),
        min_plug_repr=_repr(run.min_plug_duration_minutes),
        charging_queue_policy_repr=_repr(run.charging_queue_policy),
        vehicle_preset_repr=_repr(run.vehicle_preset),
        reposition_alpha_repr=_repr(run.reposition_alpha),
        demand_config_repr=_repr(run.demand_config),
    )

    script_path.write_text(source)
    return script_path
